import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Script from 'next/script'
import Banner from './Home/banner'
import About from './Home/About'
import Values from './Home/Navbar/Values/Values'
import Client from './Home/Client/Client'
import Service from './Home/Services/Service'
import Review from './Home/Review/Review'
import Choose from './Home/Choose/Choose'
export default function Home() {
  
  return (
    <div className={styles.container}>
      <Head>
      <title>Parasmooth Agency</title>
        <meta name="description" content="Generated by create next app" />
      
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"></link>
        <link
  rel="stylesheet"
  type="text/css"
  charset="UTF-8"
  href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
/>
<link
  rel="stylesheet"
  type="text/css"
  href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
/>
      </Head>
      <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></Script>
   
      <main className={styles.main}>
      
        <Banner/>
        <About/>
        <Service/>
        <Values/>
        <Choose/>
        <Client/>
        <Review/>
    
        </main>
    </div>
  )
}
